---
- name: Ensure apache is installed and started
  hosts: web
  become: yes
  vars:
    - httpd
  tasks:
    - name: Ensure httpd packages are present
      yum:
        name: "{{ item }}"
        state: present
      notify: restart-apache-service
  handlers:
    - name: restart-apache-service
      service:
        name: httpd
        state: restarted
