---
- name: Ensure apache is installed and started
  hosts: web
  become: yes
  tasks:
    - name: Ensure apache2 packages are present
      yum:
        name: apache2
        state: present
        update_cache: yes
      notify: restart-apache-service
  handlers:
    - name: restart-apache-service
      service:
        name: apache2
        state: restarted
