---
- name: Ensure apache is installed and started
  hosts: web
  become: yes
  tasks:
    - name: Updates apt cache
      action: apt update_cache=true
    - name: Ensure apache2 packages are present
      apt:
        name: apache2
        state: present
        
  
