---
- name: Ensure apache is installed and started
  hosts: web
  become: yes
  tasks:
    - name: Ensure apache2 packages are present
      apt:
        name: apache2
        state: present
        update_cache: yes

  
